version: '3'
services:
  frontend-devserver:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    command: ["npm","start"]