version: '3'
services:
  frontend-devserver:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    command: ["npm","start"]