# https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose/

version: '3.6'
services:
  frontend-deploy:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: testname
    ports:
      - 8080:80
    command: ["npm","run", "build"]