version: '3'
services:
  frontend-deploy:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    command: ["npm","build"]