#  https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
#  for ssh  https://circleci.com/docs/2.0/add-ssh-key/index.html?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-maxConv-auth-nb&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQjwmuiTBhDoARIsAPiv6L_LX8LLmfSCCQw61dSLNwITxXjF60Us5UvwJdLdc1hj5N6ZEKZzXzEaAmgREALw_wcB
#  https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose/

version: 2.1
jobs:
  frontend-setup:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup toolchain in container
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              sudo
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            cd frontend
            docker build -f dev.Dockerfile --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

  frontend-test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup toolchain in container
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              sudo
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Run tests
          command: |
            pwd
            docker-compose -f ./docker-compose.test.yml up


  frontend-build:
    working_directory: /app
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "34:1a:9a:b0:9f:0e:90:f7:73:ac:58:ff:06:5c:6f:52"
      - run:
          name: Setup dev container
          command: |
            apk add --no-cache \
              git \
              py3-pip \
              sudo
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: build production image
          command: |
            docker-compose -f docker-compose.deploy.yml up -d

  deploy-github:
    machine:
      image: "ubuntu-1604:202004-01"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9d:64:7a:8c:f2:68:b6:08:0c:16:93:68:7d:25:ea:ca"
      - checkout
      - run:
          name: "Build HTML"
          command: |
            pwd
            ls -a
            docker run --rm -v /home/circleci/project/:/documents/ asciidoctor/docker-asciidoctor asciidoctor /documents/warum-nein-zur-impfung.adoc
            ls -a
            abc.html index.html
            ls -a
            git config user.email "CircleCI BOT"
            git config user.name "CircleCI BOT"
            git add --all
            git commit --allow-empty -m "CircleCI - generate html [ci skip]"
            git push



workflows:
  myworkflow:
    jobs:
      - frontend-setup
      - frontend-test:
          requires:
            - frontend-setup
      - frontend-build:
          requires:
            - frontend-test